version: '3.8'

#创建一个网络
networks:
  dev-network:
    name: dev-network
    ipam:
      driver: default
      config:
        - subnet: ${IP_ADDR_PREFIX}.0/16

services:
  consul:
    container_name: consul
    image: ${CONSUL_IMAGE}
    hostname: consul.shit-code.com
    ports:
      - 8500:8500
    networks:
      dev-network:
        ipv4_address: ${IP_ADDR_PREFIX}.11
    command: ["agent",  "-config-dir", "/consul/config"]
    volumes:
      - ${DOCKER_VOLUME}/consul/node1:/consul/data
      - ${DOCKER_CONFIG}/consul/config.json:/consul/config/config.json
      - ${DOCKER_CONFIG}/consul/server.json:/consul/config/server.json
  mysql:
    container_name: mysql
    image: ${MYSQL_IMAGE}
    hostname: mysql.shit-code.com
    networks:
      dev-network:
        ipv4_address: ${IP_ADDR_PREFIX}.21
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ${DOCKER_CONFIG}/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ${DOCKER_VOLUME}/mysql:/var/lib/mysql
  redis:
    container_name: redis
    image: ${REDIS_IMAGE}
    hostname: redis.shit-code.com
    networks:
      dev-network:
        ipv4_address: ${IP_ADDR_PREFIX}.31
    ports:
      - 6379:6379
    volumes:
      - ${DOCKER_VOLUME}/redis:/data
      - ${DOCKER_CONFIG}/redis/redis.conf:/usr/local/etc/redis/redis.conf
  rabbit:
    container_name: rabbit
    image: ${RABBITMQ_IMAGE}
    hostname: rabbit.shit-code.com
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      dev-network:
        ipv4_address: ${IP_ADDR_PREFIX}.41
    volumes:
      - ${DOCKER_VOLUME}/rabbit:/var/lib/rabbitmq
  kafka:
    container_name: kafka
    image: ${KAFKA_IMAGE}
    networks:
      dev-network:
        ipv4_address: ${IP_ADDR_PREFIX}.81
    hostname: kafka.shit-code.com
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
  zipkin:
    depends_on:
      - mysql
      - rabbit
    container_name: zipkin
    image: ${ZIPKIN_IMAGE}
    hostname: zipkin.shit-code.com
    ports:
      - 9411:9411
    networks:
      dev-network:
        ipv4_address: ${IP_ADDR_PREFIX}.51
    extra_hosts:
      - mysql.shit-code.com:${IP_ADDR_PREFIX}.21
      - rabbit.shit-code.com:${IP_ADDR_PREFIX}.41
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka.shit-code.com:9092
      - KAFKA_TOPIC=zipkin
      - KAFKA_GROUP_ID=zipkin
      - KAFKA_STREAMS=1
#      - STORAGE_TYPE=mysql
#      - MYSQL_HOST=mysql.shit-code.com
#      - MYSQL_USER=root
#      - MYSQL_PASS=123456
#      - RABBIT_ADDRESSES=rabbit.shit-code.com:5672
#      - RABBIT_USER=guest
#      - RABBIT_PASSWORD=guest
#      - JAVA_OPTS=-Dlogging.level.zipkin2=DEBUG
    restart: always
    #https://raw.githubusercontent.com/openzipkin/zipkin/master/zipkin-storage/mysql-v1/src/main/resources/mysql.sql
  nginx:
    container_name: nginx
    image: ${NGINX_IMAGE}
    hostname: nginx.shit-code.com
    ports:
      - 80:80
    networks:
      dev-network:
        ipv4_address: ${IP_ADDR_PREFIX}.61
    volumes:
      - ${DOCKER_CONFIG}/logback/logback-spring.xml:/usr/share/nginx/html/logback-spring.xml
  git2consul:
    depends_on:
      - consul
    container_name: git2consul
    image: cimpress/git2consul
    hostname: git2consul.shit-code.com
    command: ['--endpoint','consul.shit-code.com','--port','8500','--config-file','/etc/git2consul.d/config.json']
    extra_hosts:
      - consul.shit-code.com:${IP_ADDR_PREFIX}.11
    networks:
      dev-network:
        ipv4_address: ${IP_ADDR_PREFIX}.71
    volumes:
      - ${DOCKER_CONFIG}/git2consul/config.json:/etc/git2consul.d/config.json
    restart: always
